// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatInfo = { chat_id: bigint, title: string, is_channel: boolean, unread_count: number, };

export type SyncChatsCommand = { limit: number, only_local: boolean, };

export type UserProfile = { id: bigint, first_name: string, last_name: string | null, username: string | null, phone_number: string | null, };
